name: pl-predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - matplotlib=3.8.4
  - pyarrow=15.0.2
  - statsmodels=0.14.2
  - xgboost=2.0.3
  - lightgbm=4.3.0
  - optuna=3.6.1
  - mlflow=2.12.1
  - joblib=1.4.2
  - pyyaml=6.0.1
  - requests=2.32.3
  - beautifulsoup4=4.12.3
  - jupyterlab=4.2.4
  - ipykernel=6.29.5
  - lxml
  - html5lib
  - pip
  - pip:
      - category-encoders==2.6.3
      - imbalanced-learn==0.12.3
      - pandera==0.18.3
      - typer==0.12.3
      - shap==0.45.1
      - ruff==0.4.10
      - black==24.4.2
      - pre-commit==3.7.1
