Arsenal: ["Arsenal", "Arsenal FC"]
Aston Villa: ["Aston Villa", "Aston Villa FC", "Villa"]
Bournemouth: ["Bournemouth", "AFC Bournemouth", "B'mouth"]
Brentford: ["Brentford", "Brentford FC"]
Brighton & Hove Albion: ["Brighton & Hove Albion", "Brighton", "Brighton and Hove Albion", "Brighton Hove Albion"]
Burnley: ["Burnley", "Burnley FC"]
Cardiff City: ["Cardiff", "Cardiff City"]
Chelsea: ["Chelsea", "Chelsea FC"]
Crystal Palace: ["Crystal Palace", "C Palace", "Crystal Palace FC", "Palace"]
Everton: ["Everton", "Everton FC"]
Fulham: ["Fulham", "Fulham FC"]
Huddersfield Town: ["Huddersfield", "Huddersfield Town"]
Leeds United: ["Leeds", "Leeds United", "Leeds Utd"]
Leicester City: ["Leicester", "Leicester City"]
Liverpool: ["Liverpool", "Liverpool FC"]
Luton Town: ["Luton", "Luton Town"]
Manchester City: ["Man City", "Manchester City", "Man. City", "ManCity"]
Manchester United: ["Man United", "Manchester United", "Man Utd", "Man. United", "ManUnited"]
Newcastle United: ["Newcastle", "Newcastle United", "Newcastle Utd"]
Norwich City: ["Norwich", "Norwich City"]
Nottingham Forest: ["Nottingham Forest", "Nott'ham Forest", "Nottm Forest", "Nott'm Forest", "Forest", "N Forest"]
Sheffield United: ["Sheffield United", "Sheffield Utd", "Sheff Utd"]
Southampton: ["Southampton", "Southampton FC", "Saints"]
Tottenham Hotspur: ["Tottenham", "Tottenham Hotspur", "Spurs", "Tottenham Hotspurs"]
Watford: ["Watford", "Watford FC"]
West Bromwich Albion: ["West Bromwich Albion", "West Brom", "WBA"]
West Ham United: ["West Ham", "West Ham United", "West Ham Utd"]
Wolverhampton Wanderers: ["Wolverhampton Wanderers", "Wolves", "Wolverhampton"]
Ipswich Town: ["Ipswich", "Ipswich Town"]
